# Archivo de configuraci칩n para Netlify

[build]
  # Directorio base donde se ejecutar치n los comandos (npm install, npm run build)
  base = "frontend"

  # Comando para construir la aplicaci칩n de React
  command = "npm run build"

  # Directorio final que Netlify debe publicar
  publish = "frontend/build"

# Regla de redirecci칩n para que funcionen las rutas de React (como /dashboard)
# Esto reemplaza y hace el mismo trabajo que el archivo _redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200