# Archivo de configuración para Netlify

[build]
  # Directorio base donde se ejecutarán los comandos
  base = "frontend"

  # Comando para construir la aplicación
  command = "npm run build"

  # Directorio final que Netlify debe publicar
  # --- CORRECCIÓN AQUÍ ---
  publish = "build"

# Regla de redirección para que funcionen las rutas de React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200